import { ArrowRight, CheckCircle2, Clock3, FileWarning, Library, MessageSquareMore } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getJsonCached } from "../../lib/api-cache";
import "./dashboard.css";

interface ReviewItem { id: string; title: string; sourceSpace: string; teamName: string; reason: string; requestedBy: string; requestedAt: string; workflowState: string; }
interface ProcessingIssue { id: string; documentId: string; title: string; sourceSpace: string; teamName: string; requestedBy: string; requestedAt: string; reason: string; }
export function DashboardPage({ canReview }: { canReview: boolean }) {
  const [reviews, setReviews] = useState<ReviewItem[]>([]); const [processingIssues, setProcessingIssues] = useState<ProcessingIssue[]>([]); const [published, setPublished] = useState(0); const [botName, setBotName] = useState("TDS");
  useEffect(() => { void Promise.all([
    canReview ? getJsonCached<{ items?: ReviewItem[] }>("/api/reviews") : Promise.resolve({ items: [] }),
    canReview ? getJsonCached<{ items?: ProcessingIssue[] }>("/api/processing-issues") : Promise.resolve({ items: [] }),
    getJsonCached<{ items?: unknown[] }>("/api/library"),
    getJsonCached<{ botName?: string }>("/api/config", 60_000),
  ]).then(([reviewData, issueData, libraryData, config]) => { setReviews(reviewData.items || []); setProcessingIssues(issueData.items || []); setPublished((libraryData.items || []).length); setBotName(config.botName || "TDS"); }); }, [canReview]);
  const attention = [...processingIssues.map((item) => ({ ...item, href: `/review?issue=${encodeURIComponent(item.id)}` })), ...reviews.map((item) => ({ ...item, href: `/review?item=${encodeURIComponent(item.id)}` }))];
  return <div className="page dashboard-page"><header className="page-heading dashboard-heading"><div><span className="eyebrow">Live knowledge workflow</span><h1>The Document Source</h1><p>{canReview ? <>{attention.length} item{attention.length === 1 ? "" : "s"} currently need attention.</> : "Search and explore approved answers available through your teams."}</p></div>{canReview && <Link className="primary-button" to="/review">Open review queue <ArrowRight size={17} /></Link>}</header>
    <section className={`status-grid ${canReview ? "" : "standard-user-status-grid"}`}>{canReview && <article className="status-card accent-cyan"><span className="status-icon"><Clock3 size={19} /></span><div><strong>{reviews.length}</strong><span>Awaiting review</span></div></article>}<article className="status-card accent-green"><span className="status-icon"><CheckCircle2 size={19} /></span><div><strong>{published}</strong><span>Published answers</span></div><small>Approved</small></article>{canReview && <article className="status-card accent-amber"><span className="status-icon"><MessageSquareMore size={19} /></span><div><strong>{reviews.filter(({ reason }) => reason === "thread_update").length}</strong><span>Thread updates</span></div></article>}{canReview && <article className="status-card accent-red"><span className="status-icon"><FileWarning size={19} /></span><div><strong>{processingIssues.length}</strong><span>Processing issues</span></div><small>No failed draft is published</small></article>}</section>
    {canReview && <section className="content-grid"><div className="panel queue-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>Live items across teams you moderate.</p></div><Link to="/review">View all <ArrowRight size={15} /></Link></div><div className="queue-list">{attention.slice(0, 5).map((item) => <Link className="queue-row" key={`${item.reason}-${item.id}`} to={item.href}><div className={`reason-mark reason-${item.reason}`}><span /></div><div className="queue-copy"><div className="row-meta"><span className="tag">{item.reason.replaceAll("_", " ")}</span><span>{item.teamName}</span></div><h3>{item.title}</h3><p>{item.sourceSpace} · Requested by {item.requestedBy}</p></div><div className="queue-time"><strong>{new Date(item.requestedAt).toLocaleDateString()}</strong></div><ArrowRight className="row-arrow" size={18} /></Link>)}{attention.length === 0 && <div className="empty-state"><p>No review items are waiting.</p></div>}</div></div>
      <aside className="side-stack"><section className="panel capture-help"><div className="panel-heading"><div><h2>Capture from Webex</h2><p>Reply inside a solved test thread with an exact bot command.</p></div></div><div className="command-block"><code>@{botName} document</code><span>New Q&amp;A</span></div><div className="command-block"><code>@{botName} update</code><span>New snapshot</span></div><p className="fine-print">Temporary AI processing is restricted to the configured synthetic test room.</p></section><Link className="library-link" to="/library"><Library size={19} /><span><strong>Browse approved knowledge</strong><small>{published} published answer{published === 1 ? "" : "s"}</small></span><ArrowRight size={17} /></Link></aside>
    </section>}</div>;
}
