import { CheckCircle2, CircleAlert, Database, LoaderCircle, ShieldCheck, Users } from "lucide-react";
import { useEffect, useState } from "react";
import "../../styles/workflow.css";

type TeamRole = "basic" | "moderator" | "admin";
interface TeamMember { id: string; displayName: string; email: string; status: string; lastSignedInAt: string | null; role: TeamRole | null }
interface IntegrationSettings { integrations: Record<"webexOAuth" | "webexCapture" | "webhook" | "supabase" | "llm", boolean>; captureRoomCount: number; botName: string; redirectUri: string | null }

export function AdminSetupPage({ section }: { section: "people" | "settings" | "help" }) {
  const [members, setMembers] = useState<TeamMember[]>([]); const [team, setTeam] = useState<{ id: string; name: string } | null>(null); const [currentUserId, setCurrentUserId] = useState(""); const [roles, setRoles] = useState<Record<string, TeamRole | "">>({}); const [message, setMessage] = useState(""); const [settings, setSettings] = useState<IntegrationSettings | null>(null); const [loading, setLoading] = useState(true);
  const content = { people: { icon: Users, eyebrow: "Administration", title: "People & teams", body: "Review registered users and manage their team-specific access roles." }, settings: { icon: Database, eyebrow: "Configuration", title: "Integration settings", body: "Live Webex, Supabase, webhook, and draft-processing status." }, help: { icon: ShieldCheck, eyebrow: "Product guide", title: "Help & FAQ", body: "Capture knowledge with an exact bot mention, review the generated draft, and publish only after human approval." } }[section]; const Icon = content.icon;
  const loadSettings = async () => { setLoading(true); try { const r = await fetch("/api/admin/integrations"); if (!r.ok) throw new Error(); setSettings(await r.json() as IntegrationSettings); } catch { setMessage("Integration status could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { if (section === "settings") void loadSettings(); }, [section]);
  useEffect(() => { if (section !== "people") return; void fetch("/api/admin/team-members").then((r) => r.json()).then((p: { team: { id: string; name: string }; currentUserId: string; items: TeamMember[] }) => { setTeam(p.team); setCurrentUserId(p.currentUserId); setMembers(p.items); setRoles(Object.fromEntries(p.items.map((m) => [m.id, m.role || ""]))); }).catch(() => setMessage("The Supabase team roster could not be loaded.")); }, [section]);
  const saveRole = async (member: TeamMember) => { const role = roles[member.id]; if (!team || !role || role === member.role) return; const r = await fetch(`/api/admin/team-members/${team.id}/${member.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ role }) }); if (r.ok) { setMembers((v) => v.map((m) => m.id === member.id ? { ...m, role, status: "active" } : m)); setMessage(`${member.displayName} is now ${role}.`); } else setMessage("Role change failed."); };
  const registerWebhook = async () => { setMessage(""); const r = await fetch("/api/admin/webex/webhook", { method: "POST", credentials: "same-origin" }); const p = await r.json() as { message?: string; code?: string }; setMessage(r.ok ? "Signed Webex automation is active." : p.message || p.code || "Webex automation could not be configured."); if (r.ok) await loadSettings(); };
  const cards = settings ? [{ key: "webexOAuth", label: "Webex sign-in", detail: "OAuth identity and secure sessions" }, { key: "webexCapture", label: "Capture identity", detail: `@${settings.botName} in ${settings.captureRoomCount} approved room${settings.captureRoomCount === 1 ? "" : "s"}` }, { key: "webhook", label: "Signed webhook", detail: "Mention events delivered from Webex" }, { key: "supabase", label: "Supabase", detail: "Private workflow and source storage" }, { key: "llm", label: "LLM processing", detail: "Redacted, source-grounded drafts" }] as const : [];
  return <div className="page admin-setup-page"><header className="page-heading"><div><span className="eyebrow">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.body}</p></div></header>{section === "people" ? <section className="panel people-panel"><div className="panel-heading"><div><h2>{team?.name || "Team members"}</h2><p>Only administrators can change roles.</p></div></div><div className="people-list">{members.map((m) => <article className="people-row" key={m.id}><span className="member-avatar">{m.displayName.slice(0, 2).toUpperCase()}</span><div className="member-identity"><strong>{m.displayName}{m.id === currentUserId && <small>You</small>}</strong><span>{m.email}</span></div><span className={`account-status status-${m.status}`}>{m.status}</span><label className="role-control"><span>Team role</span><select value={roles[m.id] || ""} disabled={m.id === currentUserId} onChange={(e) => setRoles((v) => ({ ...v, [m.id]: e.target.value as TeamRole }))}><option value="" disabled>Not assigned</option><option value="basic">Basic</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select></label><button className="primary-button role-save" disabled={m.id === currentUserId || roles[m.id] === m.role} onClick={() => void saveRole(m)}>Save role</button></article>)}</div>{message && <p className="people-message" role="status">{message}</p>}</section> : section === "settings" ? <section className="settings-dashboard">{loading && <div className="inline-status panel"><LoaderCircle className="spin" size={18} />Checking integration status…</div>}{settings && <><div className="integration-grid">{cards.map((c) => <article className="integration-card panel" key={c.key}><span className={settings.integrations[c.key] ? "integration-ready" : "integration-pending"}>{settings.integrations[c.key] ? <CheckCircle2 size={16} /> : <CircleAlert size={16} />}{settings.integrations[c.key] ? "Ready" : "Needs configuration"}</span><h2>{c.label}</h2><p>{c.detail}</p></article>)}</div><div className="setup-card panel"><h2>Webhook registration</h2><p>{settings.integrations.webhook ? "The signed mention webhook is registered." : "Register the webhook after its required integration configuration is ready."}</p>{settings.redirectUri && <p>OAuth callback: {settings.redirectUri}</p>}<button className="primary-button" disabled={!settings.integrations.webexCapture || !settings.integrations.llm} onClick={() => void registerWebhook()}>{settings.integrations.webhook ? "Re-register webhook" : "Register webhook"}</button></div></>}{message && <p className="setup-result" role="status">{message}</p>}</section> : <section className="setup-card panel"><Icon size={28} /><h2>Product workflow</h2><p>{content.body}</p><span>Protected by the current Webex-authenticated session</span></section>}</div>;
}
