import { LoaderCircle, Users } from "lucide-react";
import { useEffect, useState } from "react";
import "../../styles/workflow.css";

interface SetupData { completed: boolean; teamName: string; rooms: Array<{ id: string; title: string }> }

export function InitialSetupPage({ onComplete }: { onComplete(): void }) {
  const [data, setData] = useState<SetupData | null>(null); const [teamName, setTeamName] = useState(""); const [emails, setEmails] = useState(""); const [inviteRole, setInviteRole] = useState<"basic" | "moderator">("basic"); const [roomIds, setRoomIds] = useState<string[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void fetch("/api/admin/initial-setup").then(async (r) => { if (!r.ok) throw new Error(); return r.json() as Promise<SetupData>; }).then((payload) => { setData(payload); setTeamName(payload.teamName); if (payload.completed) onComplete(); }).catch(() => setMessage("Setup information could not be loaded.")); }, [onComplete]);
  const toggleRoom = (id: string) => setRoomIds((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const submit = async () => { setSaving(true); setMessage(""); const invitees = emails.split(/[\s,;]+/).filter(Boolean).map((email) => ({ email, role: inviteRole })); try { const r = await fetch("/api/admin/initial-setup", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ teamName, emails: invitees, roomIds }) }); const result = await r.json() as { message?: string }; if (!r.ok) throw new Error(result.message || "Setup could not be saved."); onComplete(); } catch (error) { setMessage(error instanceof Error ? error.message : "Setup could not be saved."); } finally { setSaving(false); } };
  if (!data) return <main className="auth-loading"><LoaderCircle className="spin" size={22} />Loading setup…</main>;
  return <main className="auth-loading initial-setup"><section className="setup-card panel"><Users size={28} /><span className="eyebrow">Welcome to TDS</span><h1>Set up your first team</h1><p>Choose the spaces this team may turn into moderated TDS knowledge. Pending access activates after an invitee’s approved-domain Webex sign-in.</p><label className="role-control"><span>Team name</span><input value={teamName} onChange={(e) => setTeamName(e.target.value)} placeholder="e.g. Customer Support" /></label><label className="role-control"><span>Invite team members</span><textarea value={emails} onChange={(e) => setEmails(e.target.value)} placeholder="name@tdsynnex.com&#10;Paste multiple email addresses separated by commas or new lines" rows={4} /></label><label className="role-control"><span>Role at activation</span><select value={inviteRole} onChange={(e) => setInviteRole(e.target.value as "basic" | "moderator")}><option value="basic">Basic User</option><option value="moderator">Moderator</option></select></label><div className="setup-rooms"><strong>Spaces available to the capture identity</strong>{data.rooms.map((room) => <label key={room.id}><input type="checkbox" checked={roomIds.includes(room.id)} onChange={() => toggleRoom(room.id)} />{room.title}</label>)}{data.rooms.length === 0 && <p>No group spaces are available. Add the capture identity to a Webex space, then reload this page.</p>}</div><button className="primary-button" disabled={saving || !teamName.trim() || roomIds.length === 0} onClick={() => void submit()}>{saving && <LoaderCircle className="spin" size={16} />}Complete setup</button>{message && <p className="setup-result error" role="alert">{message}</p>}</section></main>;
}
